name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cd cd74hc4067 && cargo test && cd -
    - name: Run build
      run: rustup target add thumbv6m-none-eabi && cargo build --verbose --target thumbv6m-none-eabi